config/routes.rb
Spoilerami::Application.routes.draw do
  resources :spoilers

  root :to => 'welcome#index'

end

app/models/spoiler.rb
class Spoiler < ActiveRecord::Base
  attr_accessible :film_title, :spoiler, :vote, :vote_counter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/spoilers_controller.rb
class SpoilersController < ApplicationController
  # GET /spoilers
  # GET /spoilers.json
  def index
    @spoilers = Spoiler.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spoilers }
    end
  end

  # GET /spoilers/1
  # GET /spoilers/1.json
  def show
    @spoiler = Spoiler.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spoiler }
    end
  end

  # GET /spoilers/new
  # GET /spoilers/new.json
  def new
    @spoiler = Spoiler.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spoiler }
    end
  end

  # GET /spoilers/1/edit
  def edit
    @spoiler = Spoiler.find(params[:id])
  end

  # POST /spoilers
  # POST /spoilers.json
  def create
    @spoiler = Spoiler.new(params[:spoiler])

    respond_to do |format|
      if @spoiler.save
        format.html { redirect_to @spoiler, notice: 'Spoiler was successfully created.' }
        format.json { render json: @spoiler, status: :created, location: @spoiler }
      else
        format.html { render action: "new" }
        format.json { render json: @spoiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spoilers/1
  # PUT /spoilers/1.json
  def update
    @spoiler = Spoiler.find(params[:id])

    respond_to do |format|
      if @spoiler.update_attributes(params[:spoiler])
        format.html { redirect_to @spoiler, notice: 'Spoiler was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spoiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spoilers/1
  # DELETE /spoilers/1.json
  def destroy
    @spoiler = Spoiler.find(params[:id])
    @spoiler.destroy

    respond_to do |format|
      format.html { redirect_to spoilers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spoilers_helper.rb
module SpoilersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spoilerami</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spoilers/_form.html.erb
<%= form_for(@spoiler) do |f| %>
  <% if @spoiler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spoiler.errors.count, "error") %> prohibited this spoiler from being saved:</h2>

      <ul>
      <% @spoiler.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :film_title %><br />
    <%= f.text_field :film_title %>
  </div>
  <div class="field">
    <%= f.label :spoiler %><br />
    <%= f.text_area :spoiler %>
  </div>
  <div class="field">
    <%= f.label :vote %><br />
    <%= f.text_field :vote %>
  </div>
  <div class="field">
    <%= f.label :vote_counter %><br />
    <%= f.number_field :vote_counter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spoilers/edit.html.erb
<h1>Editing spoiler</h1>

<%= render 'form' %>

<%= link_to 'Show', @spoiler %> |
<%= link_to 'Back', spoilers_path %>

app/views/spoilers/index.html.erb
<h1>Listing spoilers</h1>

<table>
  <tr>
    <th>Film title</th>
    <th>Spoiler</th>
    <th>Vote</th>
    <th>Vote counter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spoilers.each do |spoiler| %>
  <tr>
    <td><%= spoiler.film_title %></td>
    <td><%= spoiler.spoiler %></td>
    <td><%= spoiler.vote %></td>
    <td><%= spoiler.vote_counter %></td>
    <td><%= link_to 'Show', spoiler %></td>
    <td><%= link_to 'Edit', edit_spoiler_path(spoiler) %></td>
    <td><%= link_to 'Destroy', spoiler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Inserisci nuovo spoiler', new_spoiler_path %>

app/views/spoilers/new.html.erb
<h1>New spoiler</h1>

<%= render 'form' %>

<%= link_to 'Back', spoilers_path %>

app/views/spoilers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Film title:</b>
  <%= @spoiler.film_title %>
</p>

<p>
  <b>Spoiler:</b>
  <%= @spoiler.spoiler %>
</p>

<p>
  <b>Vote:</b>
  <%= @spoiler.vote %>
</p>

<p>
  <b>Vote counter:</b>
  <%= @spoiler.vote_counter %>
</p>


<%= link_to 'Edit', edit_spoiler_path(@spoiler) %> |
<%= link_to 'Back', spoilers_path %>

app/views/welcome/index.html.erb
<h1>Disclaimer</h1>
<p>Attenzione questo sito contiene spoiler di film, se decidi di continuare è a tuo rischio e pericolo</p>

<%= link_to(t(".esci"), "http://www.google.it") %>
<%= link_to(t(".entra"), spoilers_path )  %>